export {default as Blog } from './blog/Blog'
export {default as Header } from './header/Header'
export {default as Footer} from './footer/Footer'
export {default as Features} from './Features/Features'
export {default as WhatGPT3} from  './WhatGPT3/WhatGPT3'
export {default as Posibility} from './Posibility/Posibility'